version: '3'
networks:
  default:
    driver: bridge
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  backend:
    build: ./backend
    ports:
      - '8080:8080'
  proxy:
    build: ./proxy
    ports:
      - '5000:5000'
